DEFAULT_GLUON_RELEASE ?= fastd-2021.1.1+exp$(shell date '+%Y%m%d')

GLUON_RELEASE ?= $(DEFAULT_GLUON_RELEASE)

GLUON_PRIORITY ?= 0

GLUON_REGION ?= eu

GLUON_LANGS ?= en de

GLUON_DEPRECATED ?= full

GLUON_MULTIDOMAIN := 1